services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/backend 
      - ./backend:/app 
    environment:
      - DATABASE_URL=sqlite:////backend/test.db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
